In [1]:
import osmnx as ox
import geopandas as gpd
import pandas as pd

In [8]:
place = ["Linkoping, Sweden", "Stockholm, Sweden", "Goteborg, Sweden", "Malmo, Sweden", "Umea, Sweden", "Norrkoping, Sweden", "Lund, Sweden", "Uppsala, Sweden"]

In [19]:
tags = {"amenity": ["atm", "payment_terminal", "bank"]}
gdf = ox.features_from_place(place, tags)

/Users/giorgikankia/anaconda3/lib/python3.10/site-packages/osmnx/_overpass.py:211: UserWarning: This area is 67 times your configured Overpass max query area size. It will automatically be divided up into multiple sub-queries accordingly. This may take a long time.
  multi_poly_proj = utils_geo._consolidate_subdivide_geometry(poly_proj)

In [20]:
# Convert the GeoDataFrame to a pandas DataFrame
#df = pd.DataFrame(gdf)

# Set the option to display all rows
#pd.set_option("display.max_rows", None)
gdf

                         amenity     brand                   brand:wikipedia  \
element_type osmid
node         1669553200      atm  Bankomat                       sv:Bankomat
             1692398174     bank       NaN                               NaN
             1692398196     bank  Swedbank                       sv:Swedbank
             3520104777     bank    Nordea                         sv:Nordea
             3634146931     bank       SEB  sv:Skandinaviska Enskilda Banken
...                          ...       ...                               ...
             2892247326      atm       NaN                               NaN
             3173338054      atm       NaN                               NaN
             5074170119      atm       NaN                               NaN
             8267083752      atm  Bankomat                       sv:Bankomat
             11247609478     atm       NaN                               NaN

                         cash_in cash_out currency:SEK drive_through  \
element_type osmid
node         1669553200       no      yes          yes            no
             1692398174      NaN      NaN          NaN           NaN
             1692398196      NaN      NaN          NaN           NaN
             3520104777      NaN      NaN          NaN           NaN
             3634146931      NaN      NaN          NaN           NaN
...                          ...      ...          ...           ...
             2892247326      NaN      NaN          NaN           NaN
             3173338054      NaN      NaN          NaN           NaN
             5074170119      NaN      NaN          NaN           NaN
             8267083752      NaN      NaN          NaN           NaN
             11247609478      no      NaN          NaN            no

                                                 opening_hours     operator  \
element_type osmid
node         1669553200                                   24/7  Bankomat AB
             1692398174                                    NaN          NaN
             1692398196                                    NaN          NaN
             3520104777   Mo-We,Fr 10:00-15:00; Th 10:00-18:00          NaN
             3634146931                      Mo-Fr 09:00-17:00          NaN
...                                                        ...          ...
             2892247326                                    NaN          NaN
             3173338054                                    NaN          NaN
             5074170119                                    NaN          NaN
             8267083752                                    NaN  Bankomat AB
             11247609478                                   NaN     Bankomat

                             ref  ... room layer capacity office  \
element_type osmid                ...
node         1669553200   304701  ...  NaN   NaN      NaN    NaN
             1692398174      NaN  ...  NaN   NaN      NaN    NaN
             1692398196      NaN  ...  NaN   NaN      NaN    NaN
             3520104777      NaN  ...  NaN   NaN      NaN    NaN
             3634146931      NaN  ...  NaN   NaN      NaN    NaN
...                          ...  ...  ...   ...      ...    ...
             2892247326      NaN  ...  NaN   NaN      NaN    NaN
             3173338054      NaN  ...  NaN   NaN      NaN    NaN
             5074170119      NaN  ...  NaN   NaN      NaN    NaN
             8267083752      NaN  ...  NaN   NaN      NaN    NaN
             11247609478     NaN  ...  NaN   NaN      NaN    NaN

                         addr:housename survey:date internet_access  \
element_type osmid
node         1669553200             NaN         NaN             NaN
             1692398174             NaN         NaN             NaN
             1692398196             NaN         NaN             NaN
             3520104777             NaN         NaN             NaN
             3634146931             NaN         NaN             NaN
...                                 ...         ...             ...
             2892247326             NaN         NaN             NaN
             3173338054             NaN         NaN             NaN
             5074170119             NaN         NaN             NaN
             8267083752             NaN         NaN             NaN
             11247609478            NaN         NaN             NaN

                         payment:cash access contact:email
element_type osmid
node         1669553200           NaN    NaN           NaN
             1692398174           NaN    NaN           NaN
             1692398196           NaN    NaN           NaN
             3520104777           NaN    NaN           NaN
             3634146931           NaN    NaN           NaN
...                               ...    ...           ...
             2892247326           NaN    NaN           NaN
             3173338054           NaN    NaN           NaN
             5074170119           NaN    NaN           NaN
             8267083752           NaN    NaN           NaN
             11247609478          NaN    NaN           NaN

[489 rows x 59 columns]

In [21]:
gdf.reset_index([0, 1])
new_gdf = gdf.reset_index(['element_type','osmid'])
new_gdf

,element_type,osmid,amenity,brand,brand:wikipedia,cash_in,cash_out,currency:SEK,drive_through,opening_hours,...,room,layer,capacity,office,addr:housename,survey:date,internet_access,payment:cash,access,contact:email
0,node,1669553200,atm,Bankomat,sv:Bankomat,no,yes,yes,no,24/7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,node,1692398174,bank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,node,1692398196,bank,Swedbank,sv:Swedbank,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,node,3520104777,bank,Nordea,sv:Nordea,NaN,NaN,NaN,NaN,"Mo-We,Fr 10:00-15:00; Th 10:00-18:00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,node,3634146931,bank,SEB,sv:Skandinaviska Enskilda Banken,NaN,NaN,NaN,NaN,Mo-Fr 09:00-17:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,node,2892247326,atm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,node,3173338054,atm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486,node,5074170119,atm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,node,8267083752,atm,Bankomat,sv:Bankomat,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488,node,11247609478,atm,NaN,NaN,no,NaN,NaN,no,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
new_gdf.loc[new_gdf['element_type'] == "relation"]

In [22]:
# Filter the GeoDataFrame to include only nodes, aka points
nodes_gdf = new_gdf[new_gdf['geometry'].type == 'Point']
nodes_gdf

,element_type,osmid,amenity,brand,brand:wikipedia,cash_in,cash_out,currency:SEK,drive_through,opening_hours,...,room,layer,capacity,office,addr:housename,survey:date,internet_access,payment:cash,access,contact:email
0,node,1669553200,atm,Bankomat,sv:Bankomat,no,yes,yes,no,24/7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,node,1692398174,bank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,node,1692398196,bank,Swedbank,sv:Swedbank,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,node,3520104777,bank,Nordea,sv:Nordea,NaN,NaN,NaN,NaN,"Mo-We,Fr 10:00-15:00; Th 10:00-18:00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,node,3634146931,bank,SEB,sv:Skandinaviska Enskilda Banken,NaN,NaN,NaN,NaN,Mo-Fr 09:00-17:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,node,2892247326,atm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,node,3173338054,atm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486,node,5074170119,atm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,node,8267083752,atm,Bankomat,sv:Bankomat,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488,node,11247609478,atm,NaN,NaN,no,NaN,NaN,no,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# Define the file path for saving the GeoPackage file
output_file = "/Users/giorgikankia/Documents/GitHub/urbanyxliu/data collection/osm/pois-banking.geojson"

# Save the filtered GeoDataFrame to a GeoPackage file
nodes_gdf.to_file(output_file, driver='GeoJSON')